; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lopy4]
platform = espressif32
board = lopy4
framework = arduino
lib_deps = adafruit/Adafruit NeoPixel

upload_port = /dev/cu.usbmodemPy7a85be1   ; replace with your actual port
monitor_port = /dev/cu.usbmodemPy7a85be1
monitor_speed = 115200